name: Infrastructure As Code with Terraform and Ansible

on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Initialize Terraform Plan
        run: terraform init

      - name: Check Out Plan Terraform
        run: terraform plan -out=tfplan

      - name: Apply Plan Terraform
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan

      - name: Verify Andible Inventory File
        run: cat hosts.ini

      - name: Set up Ansible
        run: sudo apt install -y ansible

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Decode SSH private key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_rsa.pem
        shell: bash

      - name: Set permissions for SSH private key
        run: chmod 600 ~/.ssh/id_rsa.pem

      - name: Install K0s with Ansible Playbook
        run: ansible-playbook -i hosts.ini ansible/install_k0s.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'

      - name: Setup ControlPlane wirh Ansible Playbook
        run: ansible-playbook -i hosts.ini ansible/setup_controllplane.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
      